#!/bin/sh

FLAGS="-Wall -ansi -pedantic -ggdb"
TEMPLOG=`mktemp`

NAME=`basename $0`

case "$NAME" in
	dgcc) CC=gcc;;
	dg++) CC=g++;;
	*)
		echo "You must call this script as 'dgcc' or 'dg++'";
		exit -1;;
esac

$CC $FLAGS $* 2> "$TEMPLOG"

if [ $? -ne 0 ]; then
	echo -n "There were errors compiling. See log in (e)ditor, (s)creen or (n)o view? ([e]/s/n): "
	read c
	case $c in
		s*|S*) EDITOR=less;;
		n*|N*) exit 0;;
		*) EDITOR=vim;;
	esac

	$EDITOR "$TEMPLOG"
fi

rm -f "$TEMPLOG"
