#!/bin/sh
# Find a file with pattern $1 in name and Execute $2 on it

function usage {
	echo "Usage: `basename $0` <pattern> <command>"
	echo "Find files with <pattern> in name and execute <command> on them"
	exit 1
}

[ $# -lt 2 ] && usage

[ -n "$1" ] && name="$1" || name="*"

shift

[ -n "$1" ] && ex="$*" || ex="file"

find . -type f -iname "$name" -exec $ex '{}' \;
