#!/bin/sh

[ $# -lt 2 ] && exit 1

editor=`git var GIT_EDITOR`

[ -z "$editor" ] && exit 2

ref="$1"
path="$2"

ext=`basename "$path" | sed -e 's#^.*\.\(.*\)$#\1#'`
tmp=`mktemp --tmpdir tmp.XXXXXXXXXX.$ext`

git show "$ref:$path" > "$tmp"
"$editor" "$tmp"
rm -f "$tmp"
