#!/bin/sh

if [ $# -lt 2 ]; then
	echo "$0 <ref> <path>"
	exit 1
fi

editor="$EDITOR"
editor=${editor:-`git var GIT_EDITOR`}

if [ -z "$editor" ]; then
	echo "No editor set"
	exit 2
fi

ref="$1"
path="$2"

ext=`basename "$path" | sed -e 's#^.*\.\(.*\)$#\1#'`
tmp=`mktemp --tmpdir tmp.XXXXXXXXXX.$ext`

git show "$ref:$path" > "$tmp"
"$editor" $EDITOR_ARGS "$tmp"
rm -f "$tmp"
