#!/usr/bin/ruby

require 'webrick'

p = ENV['PORT'] || ARGV.first || 4567
d = ENV['DIR'] || ARGV.last || Dir.pwd

s = WEBrick::Utils.create_listeners nil, p

sv = WEBrick::HTTPServer.new({
  :DoNotListen => true,
  :Port => p,
  :DocumentRoot => d
})

sv.listeners.replace s

trap('INT') { sv.shutdown }
sv.start
