#!/usr/bin/ruby

require 'webrick'

p = ENV['PORT'] || ARGV.first || 4567
d = ENV['DIR'] || ARGV.last || Dir.pwd
s = WEBrick::HTTPServer.new :Port => p, :DocumentRoot => d
trap('INT') { s.shutdown }
s.start
