#!/usr/bin/ruby

require 'webrick'

a = ENV['ADDR']
p = ENV['PORT'] || 4567
d = ENV['DIR'] || Dir.pwd

s = WEBrick::Utils.create_listeners a, p

sv = WEBrick::HTTPServer.new({
  :DoNotListen => true,
  :Port => p,
  :DocumentRoot => d
})

sv.listeners.replace s

trap('INT') { sv.shutdown }
sv.start
