#!/usr/bin/env ruby

require 'sinatra'

get '/alive' do
  "He's dead, Jim."
end

post '/data/:name' do
  File.open("/tmp/#{params[:name]}", 'w') {|f| f.write(params[:content]) }
  "OK"
end

get '/data' do
  File.read(params[:name])
end
