#!/bin/sh

usage() {
	echo "Usage: $0 [options]"
	echo "Options:"
	echo -e "\t--init\tPrints the init script to be sourced by client code"
	echo -e "\t--prefix\tPrints the shlib prefix"
	echo -e "\t--help\tShow this help"
}

while true ; do
	case "$1" in
		--init) echo "$SHLIBPATH/init.sh"; exit 0;;
		--prefix) echo "$SHLIBPATH"; exit 0;;
		--help) usage; exit 0;;
		--) shift; break;;
		*) usage; exit 1;;
	esac
done
