#!/bin/bash

TPC_BIN=`which TurionPowerControl`
TPC_CONFIG="/etc/tpc.cfg"
TPC_CORES=4
LOGGER=false

if [ $UID -eq 0 ]; then
	sudo=""
else
	sudo="sudo"
fi

for mod in msr cpuid; do
	if ! lsmod | grep -q msr; then
		$sudo modprobe $mod
	fi
done

$sudo $TPC_BIN -cfgfile $TPC_CONFIG &> /dev/null
result=$?

for ((i=0;i<TPC_CORES;i++)); do
	$tpc -fo $i 4 &> /dev/null
	$tpc -fo $i 0 &> /dev/null
done

message="tpc started at `date`. result: $result"

if $LOGGER; then
	$sudo logger -t "tpc" "$message"
else
	echo "$message"
fi
