#!/bin/sh

TPC_BIN=/usr/local/sbin/TurionPowerControl
TPC_CONFIG=/etc/tpc.cfg
TPC_CORES=4
LOGGER=true

if [ `id -u` -eq 0 ]; then
	sudo=""
else
	sudo="sudo"
fi

for mod in msr cpuid; do
	if ! lsmod | grep -q msr; then
		$sudo modprobe $mod
	fi
done

$sudo "$TPC_BIN" -cfgfile "$TPC_CONFIG" > /dev/null
result=$?

core=0
while expr $core "<" $TPC_CORES > /dev/null; do
	$sudo $TPC_BIN -fo $core 4 > /dev/null
	$sudo $TPC_BIN -fo $core 0 > /dev/null
	core=`expr $core + 1`
done

message="tpc started at `date`. result: $result"

if $LOGGER; then
	$sudo logger -t "tpc" "$message"
else
	echo "$message"
fi
