#!/bin/sh

usage() {
	echo "Creates a socks5 tunnel through SSH"
	echo "Usage: $0 <socks5 port> <ssh host> [ssh port]"
}

[ $# -lt 2 ] && usage && exit 1

PORT="$1"
SSH_HOST="$2"
SSH_PORT=${3:+"-p $3"}

ssh -N -D "$PORT" $SSH_PORT "$SSH_HOST"
