#!/bin/sh
# update the documents database for faster searchs

##########################
# CONFIGURATION
##########################

# The documents directory
DOCROOT="$HOME/docs"
# The file extensions to search for
DOCEXTS=( "txt" )

#################################################
# do not touch

# The file to keep the database
# (If you change this, remember to change
# 'dbfile' in fdocs python script)
DBFILE="$HOME/.docsdb"

fargs=""

for ext in ${DOCEXTS[@]}; do
	fargs="$fargs -name *.$ext"
done

find "$DOCROOT" $fargs -type f 1> "$DBFILE" 2> /dev/null
