#!/usr/bin/python

import os, re, shutil, glob

homedir = os.environ['HOME']

keep = [
	re.compile(r'[^.].*'),
	re.compile(r'\.bash.*'),
	re.compile(r'\.dir_colors'),
	re.compile(r'\.dmrc'),
	re.compile(r'\.forward'),
	re.compile(r'\.gnupg'),
	re.compile(r'\..*vim.*'),
	re.compile(r'\.inputrc'),
	re.compile(r'\.kde.*'),
	re.compile(r'\.login'),
	re.compile(r'\.mozilla'),
	re.compile(r'\.plan'),
	re.compile(r'\.profile'),
	re.compile(r'\.project'),
	re.compile(r'\.purple'),
	re.compile(r'\.Skype'),
	re.compile(r'\.ssh'),
	re.compile(r'\.subversion'),
	re.compile(r'\.xchat.*'),
	re.compile(r'\.Xdefaults'),
	re.compile(r'\.xinitrc'),
]

remove = [
	'Desktop',
	'GNUstep',
	'.xchat2/xchatlogs/*',
	'.mozilla/firefox/k/Cache/*',
	'.mozilla/firefox/k/XPC.mfasl',
	'.mozilla/firefox/k/XUL.mfasl',
	'.mozilla/firefox/k/urlclassifier2.sqlite',
	'.kde/cache-*',
	'.kde/socket-*',
	'.kde/tmp-*',
]

def void(path):
	path = os.path.join(homedir, path)
	if os.path.isfile(path) or os.path.islink(path):
		os.unlink(path)
	elif os.path.isdir(path):
		shutil.rmtree(path)

if __name__ == '__main__':
	l = os.listdir(homedir)
	l.sort()

	for item in l:
		matches = False

		for r in keep:
			if r.match(item):
				matches = True
				break

		if not matches:
			print "removing %s" % item
			void(item)

	for item in remove:
		for i in glob.glob(os.path.join(homedir,item)):
			print "removing %s" % i
			void(i)
